Repository VolkovLabs/business-table, pull requests merged in 2025-06, with the labels that each got.

#343 Add fix for background row
  CHANGELOG.md
  src/hooks/useTable.test.tsx
  src/hooks/useTable.tsx
Labels: bug, enterprise

#344 Upgrade to Grafana 12.0 with updated dependencies
  CHANGELOG.md
  docker-compose.yml
  package-lock.json
  package.json
  src/components/Table/Table.test.tsx
  src/plugin.json
Labels: enhancement

#346 Fix the cleanup action in the ‘live’ filter
  provisioning/dashboards/panels.json
  src/components/Table/Table.tsx
  src/components/Table/hooks/useSyncedColumnFilters.test.ts
  src/components/Table/hooks/useSyncedColumnFilters.ts
  src/utils/table.test.ts
  src/utils/table.ts
Labels: bug

#347 Add the option to do striped rows
  CHANGELOG.md
  provisioning/dashboards/striped-rows.json
  src/components/Table/Table.test.tsx
  src/components/Table/Table.tsx
  src/components/Table/components/TableRow/TableRow.test.tsx
  src/components/Table/components/TableRow/TableRow.tsx
  src/components/TablePanel/TablePanel.tsx
  src/components/editors/TablesEditor/TablesEditor.tsx
  src/components/editors/TablesEditor/components/TableEditor/TableEditor.test.tsx
  src/components/editors/TablesEditor/components/TableEditor/TableEditor.tsx
  src/constants.ts
  src/migration.test.ts
  src/migration.ts
  src/types/panel.ts
  src/utils/test.ts
Labels: enhancement

#349 Add file name option for File type cell
  CHANGELOG.md
  provisioning/dashboards/file-loader.json
  src/components/Table/Table.tsx
  src/components/Table/components/CellRenderer/CellRenderer.tsx
  src/components/Table/components/CellRenderer/components/FileCellRenderer/FileCellRenderer.test.tsx
  src/components/Table/components/CellRenderer/components/FileCellRenderer/FileCellRenderer.tsx
  src/components/Table/components/TableRow/TableRow.test.tsx
  src/components/Table/components/TableRow/TableRow.tsx
  src/components/TablePanel/TablePanel.tsx
  src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.test.tsx
  src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
  src/constants.ts
  src/types/panel.ts
  src/utils/group.ts
Labels: enhancement

#352 Prepare 3.0.0 release
  README.md
  src/plugin.json
Labels: enhancement
